# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 04:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasklist', '0002_auto_20170409_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(default='', max_length=511),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[(b'TO DO', b'TO DO'), (b'DONE', b'DONE'), (b'ARCHIVED', b'ARCHIVED')], max_length=31),
        ),
    ]
